// Package docs Code generated by swaggo/swag. DO NOT EDIT
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {},
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/{owner}/{repo}": {
            "get": {
                "description": "Get information about a GitHub repository such as name, description, stars, forks, and creation date",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "repository"
                ],
                "summary": "Get repository info",
                "parameters": [
                    {
                        "type": "string",
                        "example": "\"suvorovrain\"",
                        "description": "GitHub username or organization name",
                        "name": "owner",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "string",
                        "example": "\"golang-course\"",
                        "description": "Repository name",
                        "name": "repo",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Successful response with repository info",
                        "schema": {
                            "$ref": "#/definitions/driving.GetInfoRepoOutput"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "driving.GetInfoRepoOutput": {
            "type": "object",
            "properties": {
                "count_forks": {
                    "type": "integer",
                    "example": 45
                },
                "count_stargazers": {
                    "type": "integer",
                    "example": 52
                },
                "date_creation": {
                    "type": "string",
                    "example": "Fri, 20 Aug 2021 09:38:00 UTC"
                },
                "description": {
                    "type": "string",
                    "example": "Homework for GoLang course 2026"
                },
                "name": {
                    "type": "string",
                    "example": "golang-course"
                }
            }
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "1.0.0",
	Host:             "localhost:8080",
	BasePath:         "/",
	Schemes:          []string{},
	Title:            "API Gateway",
	Description:      "API Server for getting GitHub repository information via gRPC Collector",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
