name: Setup Go

inputs:
  task:
    required: true
    type: string

runs:
  using: composite
  steps:
    - name: Setup Go
      uses: actions/setup-go@v6
      with:
        go-version: "1.25"

    - name: Install dependencies
      working-directory: ./${{ inputs.task }}
      run: go get .
