// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.34.0
// source: service.proto

package v1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type GetInfoRepoRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Owner         string                 `protobuf:"bytes,1,opt,name=owner,proto3" json:"owner,omitempty"`
	Repo          string                 `protobuf:"bytes,2,opt,name=repo,proto3" json:"repo,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetInfoRepoRequest) Reset() {
	*x = GetInfoRepoRequest{}
	mi := &file_service_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetInfoRepoRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetInfoRepoRequest) ProtoMessage() {}

func (x *GetInfoRepoRequest) ProtoReflect() protoreflect.Message {
	mi := &file_service_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetInfoRepoRequest.ProtoReflect.Descriptor instead.
func (*GetInfoRepoRequest) Descriptor() ([]byte, []int) {
	return file_service_proto_rawDescGZIP(), []int{0}
}

func (x *GetInfoRepoRequest) GetOwner() string {
	if x != nil {
		return x.Owner
	}
	return ""
}

func (x *GetInfoRepoRequest) GetRepo() string {
	if x != nil {
		return x.Repo
	}
	return ""
}

type GetInfoRepoResponse struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	Name            string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Description     string                 `protobuf:"bytes,2,opt,name=description,proto3" json:"description,omitempty"`
	DateCreation    *timestamppb.Timestamp `protobuf:"bytes,3,opt,name=date_creation,proto3" json:"date_creation,omitempty"`
	CountStargazers int32                  `protobuf:"varint,4,opt,name=count_stargazers,proto3" json:"count_stargazers,omitempty"`
	CountForks      int32                  `protobuf:"varint,5,opt,name=count_forks,proto3" json:"count_forks,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *GetInfoRepoResponse) Reset() {
	*x = GetInfoRepoResponse{}
	mi := &file_service_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetInfoRepoResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetInfoRepoResponse) ProtoMessage() {}

func (x *GetInfoRepoResponse) ProtoReflect() protoreflect.Message {
	mi := &file_service_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetInfoRepoResponse.ProtoReflect.Descriptor instead.
func (*GetInfoRepoResponse) Descriptor() ([]byte, []int) {
	return file_service_proto_rawDescGZIP(), []int{1}
}

func (x *GetInfoRepoResponse) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *GetInfoRepoResponse) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *GetInfoRepoResponse) GetDateCreation() *timestamppb.Timestamp {
	if x != nil {
		return x.DateCreation
	}
	return nil
}

func (x *GetInfoRepoResponse) GetCountStargazers() int32 {
	if x != nil {
		return x.CountStargazers
	}
	return 0
}

func (x *GetInfoRepoResponse) GetCountForks() int32 {
	if x != nil {
		return x.CountForks
	}
	return 0
}

var File_service_proto protoreflect.FileDescriptor

const file_service_proto_rawDesc = "" +
	"\n" +
	"\rservice.proto\x12\x10collector.api.v1\x1a\x1fgoogle/protobuf/timestamp.proto\">\n" +
	"\x12GetInfoRepoRequest\x12\x14\n" +
	"\x05owner\x18\x01 \x01(\tR\x05owner\x12\x12\n" +
	"\x04repo\x18\x02 \x01(\tR\x04repo\"\xdb\x01\n" +
	"\x13GetInfoRepoResponse\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12 \n" +
	"\vdescription\x18\x02 \x01(\tR\vdescription\x12@\n" +
	"\rdate_creation\x18\x03 \x01(\v2\x1a.google.protobuf.TimestampR\rdate_creation\x12*\n" +
	"\x10count_stargazers\x18\x04 \x01(\x05R\x10count_stargazers\x12 \n" +
	"\vcount_forks\x18\x05 \x01(\x05R\vcount_forks2o\n" +
	"\x0fInfoRepoService\x12\\\n" +
	"\vGetInfoRepo\x12$.collector.api.v1.GetInfoRepoRequest\x1a%.collector.api.v1.GetInfoRepoResponse\"\x00BCZAgithub.com/Friend-zva/golang-course-task2/collector/pkg/api/v1;v1b\x06proto3"

var (
	file_service_proto_rawDescOnce sync.Once
	file_service_proto_rawDescData []byte
)

func file_service_proto_rawDescGZIP() []byte {
	file_service_proto_rawDescOnce.Do(func() {
		file_service_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_service_proto_rawDesc), len(file_service_proto_rawDesc)))
	})
	return file_service_proto_rawDescData
}

var file_service_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_service_proto_goTypes = []any{
	(*GetInfoRepoRequest)(nil),    // 0: collector.api.v1.GetInfoRepoRequest
	(*GetInfoRepoResponse)(nil),   // 1: collector.api.v1.GetInfoRepoResponse
	(*timestamppb.Timestamp)(nil), // 2: google.protobuf.Timestamp
}
var file_service_proto_depIdxs = []int32{
	2, // 0: collector.api.v1.GetInfoRepoResponse.date_creation:type_name -> google.protobuf.Timestamp
	0, // 1: collector.api.v1.InfoRepoService.GetInfoRepo:input_type -> collector.api.v1.GetInfoRepoRequest
	1, // 2: collector.api.v1.InfoRepoService.GetInfoRepo:output_type -> collector.api.v1.GetInfoRepoResponse
	2, // [2:3] is the sub-list for method output_type
	1, // [1:2] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_service_proto_init() }
func file_service_proto_init() {
	if File_service_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_service_proto_rawDesc), len(file_service_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_service_proto_goTypes,
		DependencyIndexes: file_service_proto_depIdxs,
		MessageInfos:      file_service_proto_msgTypes,
	}.Build()
	File_service_proto = out.File
	file_service_proto_goTypes = nil
	file_service_proto_depIdxs = nil
}
