// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.1
// - protoc             v7.34.0
// source: service.proto

package v1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	InfoRepoService_GetInfoRepo_FullMethodName = "/collector.api.v1.InfoRepoService/GetInfoRepo"
)

// InfoRepoServiceClient is the client API for InfoRepoService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type InfoRepoServiceClient interface {
	GetInfoRepo(ctx context.Context, in *GetInfoRepoRequest, opts ...grpc.CallOption) (*GetInfoRepoResponse, error)
}

type infoRepoServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewInfoRepoServiceClient(cc grpc.ClientConnInterface) InfoRepoServiceClient {
	return &infoRepoServiceClient{cc}
}

func (c *infoRepoServiceClient) GetInfoRepo(ctx context.Context, in *GetInfoRepoRequest, opts ...grpc.CallOption) (*GetInfoRepoResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetInfoRepoResponse)
	err := c.cc.Invoke(ctx, InfoRepoService_GetInfoRepo_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// InfoRepoServiceServer is the server API for InfoRepoService service.
// All implementations must embed UnimplementedInfoRepoServiceServer
// for forward compatibility.
type InfoRepoServiceServer interface {
	GetInfoRepo(context.Context, *GetInfoRepoRequest) (*GetInfoRepoResponse, error)
	mustEmbedUnimplementedInfoRepoServiceServer()
}

// UnimplementedInfoRepoServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedInfoRepoServiceServer struct{}

func (UnimplementedInfoRepoServiceServer) GetInfoRepo(context.Context, *GetInfoRepoRequest) (*GetInfoRepoResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetInfoRepo not implemented")
}
func (UnimplementedInfoRepoServiceServer) mustEmbedUnimplementedInfoRepoServiceServer() {}
func (UnimplementedInfoRepoServiceServer) testEmbeddedByValue()                         {}

// UnsafeInfoRepoServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to InfoRepoServiceServer will
// result in compilation errors.
type UnsafeInfoRepoServiceServer interface {
	mustEmbedUnimplementedInfoRepoServiceServer()
}

func RegisterInfoRepoServiceServer(s grpc.ServiceRegistrar, srv InfoRepoServiceServer) {
	// If the following call panics, it indicates UnimplementedInfoRepoServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&InfoRepoService_ServiceDesc, srv)
}

func _InfoRepoService_GetInfoRepo_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetInfoRepoRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(InfoRepoServiceServer).GetInfoRepo(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: InfoRepoService_GetInfoRepo_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(InfoRepoServiceServer).GetInfoRepo(ctx, req.(*GetInfoRepoRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// InfoRepoService_ServiceDesc is the grpc.ServiceDesc for InfoRepoService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var InfoRepoService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "collector.api.v1.InfoRepoService",
	HandlerType: (*InfoRepoServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetInfoRepo",
			Handler:    _InfoRepoService_GetInfoRepo_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "service.proto",
}
