name: Task template

on:
  workflow_call:
    inputs:
      task:
        required: true
        type: string

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}-${{ inputs.task }}
  cancel-in-progress: true

jobs:
  formatter:
    name: Formatter
    runs-on: ubuntu-latest

    steps:
      - name: Clone project
        uses: actions/checkout@v6
      - uses: ./.github/actions/setup-go

      - name: Run gofmt
        working-directory: ./${{ inputs.task }}
        run: gofmt -d .

  linter:
    name: Linter
    runs-on: ubuntu-latest

    steps:
      - name: Clone project
        uses: actions/checkout@v6
      - uses: ./.github/actions/setup-go

      - name: Run golangci-lint
        uses: golangci/golangci-lint-action@v3
        with:
          working-directory: ./${{ inputs.task }}

  tests:
    name: Build
    runs-on: ubuntu-latest

    steps:
      - name: Clone project
        uses: actions/checkout@v6
      - uses: ./.github/actions/setup-go

      - name: Build
        working-directory: ./${{ inputs.task }}
        run: go build -v
